LPS-121753 Fix no-use-before-define violations in layout-content-page-editor-web
Now that we aren't transforming the code for IE, these `const` actually
remain as `const` instead of getting turned into `var`, which exposes a
use-before-definition problem at runtime:

    ReferenceError: Cannot access 'ExperimentStatusType' before initialization

So I fixed this one by hand. As a bonus, moving the declaration of
`ExperimentStatusType` before its usage ends up putting the exports into
alphabetical order.

For reference:

- types.js before dropping IE support: https://gist.github.com/wincent/d5889bfca7242d1093647b824345a785
- types.js after dropping IE support: https://gist.github.com/wincent/4ecfb9caa974089fdfd0b9a0eb6ff8e7
- diff: https://gist.github.com/wincent/ca06919af8471c3faeff5120854448d6

It's possible that we'll run into other subtle issues of this type at
runtime; so, I'm going to see whether ESLint's no-use-before-define rule
can help us out here, at least for JS in ".js" files (it won't help us
in JSPs because we can't treat those as self-contained lexical units):

    https://eslint.org/docs/rules/no-use-before-define

In a quick test of activating that rule, it finds over 360 problems that
we're going to have to deal with:

    https://gist.github.com/wincent/34bb65530fc4baccfc33922c83e3a79d

And I am going to do that in this and following commits.

This one fixes the error above that I found manually, plus all of the
other errors in layout-content-page-editor-web found by ESLint:

Fixes:

    app/components/AllowedFragmentSelector.js|27 col 9 error| 'toFragmentEntryKeysArray' was used before it was defined.  no-use-before-define
    app/components/AllowedFragmentSelector.js|40 col 30 error| 'toNodes' was used before it was defined.  no-use-before-define
    app/components/AllowedFragmentSelector.js|47 col 3 error| 'getSelectedNodeIds' was used before it was defined.  no-use-before-define
    app/components/AllowedFragmentSelector.js|55 col 32 error| 'getSelectedNodeIds' was used before it was defined.  no-use-before-define
    app/components/SaveFragmentCompositionModal.js|73 col 4 error| 'setLoading' was used before it was defined.  no-use-before-define
    app/components/SaveFragmentCompositionModal.js|98 col 6 error| 'setLoading' was used before it was defined.  no-use-before-define
    app/components/Sidebar.js|83 col 5 error| 'togglePlugin' was used before it was defined.  no-use-before-define
    app/reducers/index.js|40 col 10 error| 'combinedReducer' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|37 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|59 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|78 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|98 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|126 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|156 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|179 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|206 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|228 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/services/LayoutService.js|255 col 10 error| 'layoutServiceFetch' was used before it was defined.  no-use-before-define
    app/thunks/multipleUndo.js|50 col 9 error| 'isUndoAction' was used before it was defined.  no-use-before-define
    plugins/comments/components/FragmentComment.js|92 col 6 error| 'hideComment' was used before it was defined.  no-use-before-define
    plugins/experience/index.js|34 col 60 error| 'Experience' was used before it was defined.  no-use-before-define
    plugins/fragments-widgets/components/FragmentsSidebar.js|38 col 7 error| 'normalizeFragmentEntry' was used before it was defined.  no-use-before-define
    plugins/fragments-widgets/components/FragmentsSidebar.js|50 col 6 error| 'normalizeCollections' was used before it was defined.  no-use-before-define
    plugins/fragments-widgets/components/FragmentsSidebar.js|64 col 21 error| 'collectionFilter' was used before it was defined.  no-use-before-define
    plugins/fragments-widgets/components/FragmentsSidebar.js|94 col 37 error| 'normalizeWidget' was used before it was defined.  no-use-before-define
    plugins/page-structure/components/PageStructureSidebarSection.js|51 col 48 error| 'handleResize' was used before it was defined.  no-use-before-define
    plugins/page-structure/components/PageStructureSidebarSection.js|52 col 49 error| 'handleResizeEnd' was used before it was defined.  no-use-before-define
    plugins/page-structure/components/PageStructureSidebarSection.js|53 col 46 error| 'handleResizeEnd' was used before it was defined.  no-use-before-define
    plugins/page-structure/components/item-configuration-panels/RowGeneralPanel.js|53 col 35 error| 'rowConfig' was used before it was defined.  no-use-before-define