LPS-84119 seems to need JSONObject, see error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/json/JSONObject
	at com.liferay.source.formatter.SourceFormatter._isPortalSource(SourceFormatter.java:800)
	at com.liferay.source.formatter.SourceFormatter._init(SourceFormatter.java:705)
	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:303)
	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:267)
Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.json.JSONObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more