LPS-96877 portal-template-freemarker: Need to bump portal-kernel version to the minimum level that contains the changes of LPS-84138 otherwise FreeMarkerTemplateTests fail because we bumped portal-impl to "default" earlier
com.liferay.portal.template.freemarker.internal.FreeMarkerTemplateTest > testProcessTemplate8 FAILED
    java.lang.NoSuchMethodError: com.liferay.portal.kernel.cache.PortalCacheHelperUtil.getPortalCache(Ljava/lang/String;Ljava/lang/String;)Lcom/liferay/portal/kernel/cache/PortalCache;
        at com.liferay.portal.template.TemplateResourcePortalCacheListener.<init>(TemplateResourcePortalCacheListener.java:42)
        at com.liferay.portal.template.DefaultTemplateResourceLoader.<init>(DefaultTemplateResourceLoader.java:80)
        at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplateResourceLoader.activate(FreeMarkerTemplateResourceLoader.java:87)
        at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplateTest.setUp(FreeMarkerTemplateTest.java:80)