LPS-77425 SF seems to need petra.string
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:301)
        at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:216)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:125)
        at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:678)
        at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:64)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:287)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:283)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:659)
        at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:68)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:114)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:110)
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: com/liferay/petra/string/StringBundler
        at com.liferay.source.formatter.parser.JavaSignature.toString(JavaSignature.java:52)
        at com.liferay.source.formatter.checks.JavaAPISignatureCheck._isException(JavaAPISignatureCheck.java:136)
        at com.liferay.source.formatter.checks.JavaAPISignatureCheck.doProcess(JavaAPISignatureCheck.java:76)
        at com.liferay.source.formatter.checks.BaseJavaTermCheck._walkJavaClass(BaseJavaTermCheck.java:160)
        at com.liferay.source.formatter.checks.BaseJavaTermCheck.process(BaseJavaTermCheck.java:41)
        at com.liferay.source.formatter.checks.util.SourceChecksUtil._processJavaTermCheck(SourceChecksUtil.java:317)
        at com.liferay.source.formatter.checks.util.SourceChecksUtil.processSourceChecks(SourceChecksUtil.java:151)
        at com.liferay.source.formatter.BaseSourceProcessor._processSourceChecks(BaseSourceProcessor.java:669)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:298)
        at com.liferay.source.formatter.JavaSourceProcessor.format(JavaSourceProcessor.java:73)
        at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:550)
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:647)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.liferay.petra.string.StringBundler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)