LPS-103851 prevent split packages, caused by 24229a92cf39e37a3ce7f5e665ff4c3ab41d9c7f see https://github.com/brianchandotcom/liferay-portal/pull/80300
junit.framework.AssertionFailedError: Detected split packages in modules/apps/layout/layout-service and modules/apps/layout/layout-impl: [com.liferay.layout.internal.model.listener]
	at com.liferay.portal.split.packages.SplitPackagesTest._checkSplitPackages(SplitPackagesTest.java:138)
	at com.liferay.portal.split.packages.SplitPackagesTest.access$000(SplitPackagesTest.java:43)
	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:96)
	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:65)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.split.packages.SplitPackagesTest.testSplitPackage(SplitPackagesTest.java:63)