LPS-84119 JSONSerializable: Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/json/JSONSerializable 	at java.lang.ClassLoader.defineClass1(Native Method) 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at com.liferay.source.formatter.SourceFormatter._isPortalSource(SourceFormatter.java:800) 	at com.liferay.source.formatter.SourceFormatter._init(SourceFormatter.java:705) 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:303) 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:267) Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.json.JSONSerializable 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 16 more