LPS-100269 portal-search: FIX: java.lang.NoClassDefFoundError: com/liferay/petra/function/UnsafeFunction
ResourcePermissionLocalService now imports UnsafeFunction. (https://github.com/liferay/liferay-portal/commit/689e05430bc71a928244ae7274ae7a0c7bf9f508#diff-3ebe1a1e87873b409cd7dc277200f991R17)

Hence, build.gradle needs petra-function for ultra-fast clone-and-test "gradlew test", as performed by Search CI Server. (no "ant all" at all.)

https://issues.liferay.com/browse/LPS-100269